import io
import uuid

from PIL import Image

from tests.test_entries import utc_naive_days_ago


def make_jpeg(width=64, height=48) -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (width, height), "red").save(buf, format="JPEG")
    return buf.getvalue()


def make_png() -> bytes:
    buf = io.BytesIO()
    Image.new("RGBA", (32, 32), (0, 255, 0, 255)).save(buf, format="PNG")
    return buf.getvalue()


# Valid EBML/WebM magic bytes followed by padding (ffmpeg-less test stub)
FAKE_WEBM = b"\x1a\x45\xdf\xa3" + b"\x00" * 256


def upload(client, obra_id, headers, filename="foto.jpg", content=None, caption=None):
    files = [("files", (filename, content if content is not None else make_jpeg(), "application/octet-stream"))]
    data = {}
    if caption is not None:
        data["caption"] = caption
    return client.post(
        f"/api/v1/obras/{obra_id}/media", files=files, data=data, headers=headers
    )


def test_upload_photo_creates_media_and_thumbnail(client, worker_headers, obra):
    res = upload(client, obra.id, worker_headers, caption="fachada")
    assert res.status_code == 201
    (item,) = res.json()
    assert item["kind"] == "photo"
    assert item["mime_type"] == "image/jpeg"
    assert item["original_filename"] == "foto.jpg"
    assert item["caption"] == "fachada"

    # Thumbnail generated by the background task right after the response
    res = client.get(f"/api/v1/media/{item['id']}/thumb", headers=worker_headers)
    assert res.status_code == 200
    assert res.headers["content-type"] == "image/jpeg"


def test_upload_png_accepted(client, worker_headers, obra):
    res = upload(client, obra.id, worker_headers, filename="captura.png", content=make_png())
    assert res.status_code == 201
    assert res.json()[0]["mime_type"] == "image/png"


def test_upload_video_webm_accepted(client, worker_headers, obra):
    res = upload(client, obra.id, worker_headers, filename="video.webm", content=FAKE_WEBM)
    assert res.status_code == 201
    assert res.json()[0]["kind"] == "video"


def test_upload_rejects_wrong_magic_bytes(client, worker_headers, obra):
    res = upload(
        client, obra.id, worker_headers,
        filename="malware.jpg", content=b"MZ\x90\x00 not an image",
    )
    assert res.status_code == 400


def test_upload_rejects_oversized_photo(client, worker_headers, obra):
    big = b"\xff\xd8\xff\xe0" + b"\x00" * (16 * 1024 * 1024)
    res = upload(client, obra.id, worker_headers, content=big)
    assert res.status_code == 400
    assert "15 MB" in res.json()["detail"]


def test_upload_to_unassigned_obra_forbidden(client, worker_headers, other_obra):
    res = upload(client, other_obra.id, worker_headers)
    assert res.status_code == 403


def test_multiple_files_in_one_request(client, worker_headers, obra):
    files = [
        ("files", ("a.jpg", make_jpeg(), "image/jpeg")),
        ("files", ("b.jpg", make_jpeg(), "image/jpeg")),
    ]
    res = client.post(
        f"/api/v1/obras/{obra.id}/media", files=files, headers=worker_headers
    )
    assert res.status_code == 201
    assert len(res.json()) == 2


def test_list_media_with_filters_and_pagination(
    client, worker_headers, admin_headers, obra, worker
):
    upload(client, obra.id, worker_headers)
    upload(client, obra.id, worker_headers, filename="video.webm", content=FAKE_WEBM)
    upload(client, obra.id, admin_headers, filename="jefe.jpg")

    res = client.get(f"/api/v1/obras/{obra.id}/media", headers=admin_headers)
    assert res.status_code == 200
    assert res.json()["total"] == 3

    res = client.get(f"/api/v1/obras/{obra.id}/media?kind=photo", headers=admin_headers)
    assert res.json()["total"] == 2

    res = client.get(
        f"/api/v1/obras/{obra.id}/media?user_id={worker.id}", headers=admin_headers
    )
    assert res.json()["total"] == 2

    res = client.get(
        f"/api/v1/obras/{obra.id}/media?page=1&page_size=2", headers=admin_headers
    )
    data = res.json()
    assert len(data["items"]) == 2
    assert data["pages"] == 2


def test_worker_cannot_list_media_of_unassigned_obra(
    client, worker_headers, other_obra
):
    res = client.get(f"/api/v1/obras/{other_obra.id}/media", headers=worker_headers)
    assert res.status_code == 403


def test_download_file_supports_range(client, worker_headers, obra):
    item = upload(
        client, obra.id, worker_headers, filename="video.webm", content=FAKE_WEBM
    ).json()[0]

    res = client.get(f"/api/v1/media/{item['id']}/file", headers=worker_headers)
    assert res.status_code == 200
    assert res.content == FAKE_WEBM

    res = client.get(
        f"/api/v1/media/{item['id']}/file",
        headers={**worker_headers, "Range": "bytes=0-9"},
    )
    assert res.status_code == 206
    assert len(res.content) == 10


def test_worker_cannot_download_media_of_unassigned_obra(
    client, worker_headers, admin_headers, other_obra
):
    item = upload(client, other_obra.id, admin_headers).json()[0]
    res = client.get(f"/api/v1/media/{item['id']}/file", headers=worker_headers)
    assert res.status_code == 403


def test_download_requires_auth(client, worker_headers, obra):
    item = upload(client, obra.id, worker_headers).json()[0]
    res = client.get(f"/api/v1/media/{item['id']}/file")
    assert res.status_code == 401


def test_author_edits_caption_other_worker_cannot(
    client, worker_headers, worker2_headers, admin_headers, obra, worker2
):
    item = upload(client, obra.id, worker_headers).json()[0]
    client.post(
        f"/api/v1/obras/{obra.id}/assignments",
        json={"add": [str(worker2.id)]},
        headers=admin_headers,
    )

    res = client.patch(
        f"/api/v1/media/{item['id']}", json={"caption": "nueva"}, headers=worker_headers
    )
    assert res.status_code == 200
    assert res.json()["caption"] == "nueva"

    res = client.patch(
        f"/api/v1/media/{item['id']}", json={"caption": "x"}, headers=worker2_headers
    )
    assert res.status_code == 403

    res = client.patch(
        f"/api/v1/media/{item['id']}", json={"caption": "admin"}, headers=admin_headers
    )
    assert res.status_code == 200


def test_author_deletes_own_media_within_48h(client, worker_headers, obra):
    item = upload(client, obra.id, worker_headers).json()[0]
    res = client.delete(f"/api/v1/media/{item['id']}", headers=worker_headers)
    assert res.status_code == 204
    res = client.get(f"/api/v1/media/{item['id']}/file", headers=worker_headers)
    assert res.status_code == 404


def test_author_cannot_delete_after_48h_but_admin_can(
    client, worker_headers, admin_headers, obra, db_session
):
    from app.models import MediaFile

    item = upload(client, obra.id, worker_headers).json()[0]
    media = db_session.get(MediaFile, uuid.UUID(item["id"]))
    media.uploaded_at = utc_naive_days_ago(3)
    db_session.add(media)
    db_session.commit()

    res = client.delete(f"/api/v1/media/{item['id']}", headers=worker_headers)
    assert res.status_code == 403

    res = client.delete(f"/api/v1/media/{item['id']}", headers=admin_headers)
    assert res.status_code == 204


def test_other_worker_cannot_delete(
    client, worker_headers, worker2_headers, admin_headers, obra, worker2
):
    item = upload(client, obra.id, worker_headers).json()[0]
    client.post(
        f"/api/v1/obras/{obra.id}/assignments",
        json={"add": [str(worker2.id)]},
        headers=admin_headers,
    )
    res = client.delete(f"/api/v1/media/{item['id']}", headers=worker2_headers)
    assert res.status_code == 403


def test_export_obra_media_zip(client, worker_headers, admin_headers, obra):
    import zipfile

    upload(client, obra.id, worker_headers, filename="a.jpg")
    upload(client, obra.id, worker_headers, filename="b.jpg")

    res = client.get(f"/api/v1/obras/{obra.id}/media/export.zip", headers=admin_headers)
    assert res.status_code == 200
    assert res.headers["content-type"] == "application/zip"
    zf = zipfile.ZipFile(io.BytesIO(res.content))
    names = zf.namelist()
    assert len(names) == 2
    assert "a.jpg" in names and "b.jpg" in names


def test_export_zip_requires_admin(client, worker_headers, obra):
    res = client.get(f"/api/v1/obras/{obra.id}/media/export.zip", headers=worker_headers)
    assert res.status_code == 403


def test_export_zip_empty_obra_returns_404(client, admin_headers, obra):
    res = client.get(f"/api/v1/obras/{obra.id}/media/export.zip", headers=admin_headers)
    assert res.status_code == 404


def test_recent_media_admin_only(client, worker_headers, admin_headers):
    res = client.get("/api/v1/media/recent", headers=worker_headers)
    assert res.status_code == 403
    res = client.get("/api/v1/media/recent", headers=admin_headers)
    assert res.status_code == 200
    assert res.json() == []
